# Generated by Django 5.2.5 on 2025-10-08 13:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "firstname",
                    models.CharField(
                        help_text="Enter employee's first name",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="First Name",
                    ),
                ),
                (
                    "lastname",
                    models.CharField(
                        help_text="Enter employee's last name",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="Last Name",
                    ),
                ),
                (
                    "othername",
                    models.CharField(
                        blank=True,
                        help_text="Enter employee's other name (optional)",
                        max_length=100,
                        null=True,
                        verbose_name="Other Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Enter valid email address",
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Enter phone number (optional)",
                        max_length=15,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique employee ID (optional)",
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Employee ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        help_text="Enter department name",
                        max_length=100,
                        verbose_name="Department",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Enter job role",
                        max_length=100,
                        verbose_name="Job Role",
                    ),
                ),
                (
                    "join_date",
                    models.DateField(
                        blank=True,
                        help_text="Select join date",
                        null=True,
                        verbose_name="Join Date",
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Enter salary amount",
                        max_digits=10,
                        null=True,
                        verbose_name="Salary",
                    ),
                ),
                (
                    "dob",
                    models.DateField(
                        help_text="Select date of birth", verbose_name="Date of Birth"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        help_text="Select gender",
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        help_text="Enter state", max_length=50, verbose_name="State"
                    ),
                ),
                (
                    "lga",
                    models.CharField(
                        help_text="Enter Local Government Area",
                        max_length=50,
                        verbose_name="LGA",
                    ),
                ),
                (
                    "ward",
                    models.CharField(
                        help_text="Enter ward", max_length=100, verbose_name="Ward"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Suspended", "Suspended"),
                            ("On Leave", "On Leave"),
                        ],
                        default="Active",
                        help_text="Select employee status",
                        max_length=20,
                        verbose_name="Employment Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["lastname", "firstname"],
                        name="employee_em_lastnam_ca3ce4_idx",
                    ),
                    models.Index(
                        fields=["department"], name="employee_em_departm_26167f_idx"
                    ),
                    models.Index(
                        fields=["status"], name="employee_em_status_33d5fd_idx"
                    ),
                    models.Index(fields=["email"], name="employee_em_email_9e89e3_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("email",), name="unique_employee_email"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("employee_id__isnull", False)),
                        fields=("employee_id",),
                        name="unique_employee_id_when_not_null",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter department name",
                        max_length=100,
                        unique=True,
                        verbose_name="Department Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Enter department description",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        help_text="Select department manager",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_departments",
                        to="employee.employee",
                        verbose_name="Department Manager",
                    ),
                ),
            ],
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        help_text="Enter note about employee", verbose_name="Note"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(
                        help_text="Enter your name",
                        max_length=100,
                        verbose_name="Created By",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Select employee",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="employee.employee",
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employee Note",
                "verbose_name_plural": "Employee Notes",
                "ordering": ["-created_at"],
            },
        ),
    ]
